# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import llm_pb2 as llm__pb2


class LLMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateFirstQuestion = channel.unary_unary(
                '/llm.LLMService/GenerateFirstQuestion',
                request_serializer=llm__pb2.SessionState.SerializeToString,
                response_deserializer=llm__pb2.LLMQuestionResponse.FromString,
                )
        self.GenerateNextQuestion = channel.unary_unary(
                '/llm.LLMService/GenerateNextQuestion',
                request_serializer=llm__pb2.SessionState.SerializeToString,
                response_deserializer=llm__pb2.LLMQuestionResponse.FromString,
                )
        self.GenerateFinalGuess = channel.unary_unary(
                '/llm.LLMService/GenerateFinalGuess',
                request_serializer=llm__pb2.SessionState.SerializeToString,
                response_deserializer=llm__pb2.LLMGuessResponse.FromString,
                )


class LLMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateFirstQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateNextQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateFinalGuess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateFirstQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateFirstQuestion,
                    request_deserializer=llm__pb2.SessionState.FromString,
                    response_serializer=llm__pb2.LLMQuestionResponse.SerializeToString,
            ),
            'GenerateNextQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateNextQuestion,
                    request_deserializer=llm__pb2.SessionState.FromString,
                    response_serializer=llm__pb2.LLMQuestionResponse.SerializeToString,
            ),
            'GenerateFinalGuess': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateFinalGuess,
                    request_deserializer=llm__pb2.SessionState.FromString,
                    response_serializer=llm__pb2.LLMGuessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateFirstQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm.LLMService/GenerateFirstQuestion',
            llm__pb2.SessionState.SerializeToString,
            llm__pb2.LLMQuestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateNextQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm.LLMService/GenerateNextQuestion',
            llm__pb2.SessionState.SerializeToString,
            llm__pb2.LLMQuestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateFinalGuess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm.LLMService/GenerateFinalGuess',
            llm__pb2.SessionState.SerializeToString,
            llm__pb2.LLMGuessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
