# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x03llm\"&\n\x02QA\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\"\xcb\x01\n\x0cSessionState\x12\x11\n\tsessionId\x18\x01 \x01(\t\x12\x15\n\rquestionCount\x18\x02 \x01(\x05\x12\x18\n\x07history\x18\x03 \x03(\x0b\x32\x07.llm.QA\x12?\n\x0f\x63\x61ndidateScores\x18\x04 \x03(\x0b\x32&.llm.SessionState.CandidateScoresEntry\x1a\x36\n\x14\x43\x61ndidateScoresEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\'\n\x13LLMQuestionResponse\x12\x10\n\x08question\x18\x01 \x01(\t\"K\n\x10LLMGuessResponse\x12\r\n\x05guess\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x14\n\x0c\x61lternatives\x18\x03 \x03(\t2\xd7\x01\n\nLLMService\x12\x44\n\x15GenerateFirstQuestion\x12\x11.llm.SessionState\x1a\x18.llm.LLMQuestionResponse\x12\x43\n\x14GenerateNextQuestion\x12\x11.llm.SessionState\x1a\x18.llm.LLMQuestionResponse\x12>\n\x12GenerateFinalGuess\x12\x11.llm.SessionState\x1a\x15.llm.LLMGuessResponseBCZAgithub.com/suhas-developer07/GuessVibe-Server/generated/proto/llmb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub.com/suhas-developer07/GuessVibe-Server/generated/proto/llm'
  _globals['_SESSIONSTATE_CANDIDATESCORESENTRY']._options = None
  _globals['_SESSIONSTATE_CANDIDATESCORESENTRY']._serialized_options = b'8\001'
  _globals['_QA']._serialized_start=18
  _globals['_QA']._serialized_end=56
  _globals['_SESSIONSTATE']._serialized_start=59
  _globals['_SESSIONSTATE']._serialized_end=262
  _globals['_SESSIONSTATE_CANDIDATESCORESENTRY']._serialized_start=208
  _globals['_SESSIONSTATE_CANDIDATESCORESENTRY']._serialized_end=262
  _globals['_LLMQUESTIONRESPONSE']._serialized_start=264
  _globals['_LLMQUESTIONRESPONSE']._serialized_end=303
  _globals['_LLMGUESSRESPONSE']._serialized_start=305
  _globals['_LLMGUESSRESPONSE']._serialized_end=380
  _globals['_LLMSERVICE']._serialized_start=383
  _globals['_LLMSERVICE']._serialized_end=598
# @@protoc_insertion_point(module_scope)
